#!/usr/bin/env bash
# Shows information about subdomains.

get_record_info() {
  local domain="$1"
  local subdomain="$2"

  dig_output=$(dig "$subdomain.$domain" | awk '/^'${subdomain}.${domain}'\./{flag=1;next}/^$/{flag=0}flag')

  record_type=$(echo "$dig_output" | awk '{print $4}')
  destination=$(echo "$dig_output" | awk '{print $5}')

  echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  get_record_info "$domain" "www"
  get_record_info "$domain" "lb-01"
  get_record_info "$domain" "web-01"
  get_record_info "$domain" "web-02"
else
  get_record_info "$domain" "$subdomain"
fi
