#!/usr/bin/env bash
# Shows information about subdomains.

domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig "$subdomain"."$domain" | awk '/^'"$subdomain"'.'"$domain"'\./{print $0}')
    record_type=$(echo "$line" | awk '{print $4}')
    destination=$(echo "$line" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
