#!/usr/bin/env bash
# A bash script that installs nginx on an Ubuntu machine.
# This script also configures the default webpage served to be "Hello World!"
# When the request URL matches /redirectme, it redirects to my GitHub homepage.

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

string_for_replacement="server_name _;\n\trewrite ^\/redirectme https:\/\/github.com\/egborojie permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
