#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.


sudo apt-get update -y
sudo apt-get install -y haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg
sudo chmod 666 /etc/haproxy/haproxy.cfg

echo "global
                log /dev/log    local0
                log /dev/log    local1 notice
                chroot /var/lib/haproxy
                stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
                stats timeout 30s
                user haproxy
                group haproxy
                daemon

defaults
                log             global
                mode    http
                option  httplog
                option  dontlognull
                timeout connect 5000
                timeout client  50000
                timeout server  50000

frontend http-in
                bind *:80
                default_backend servers

backend servers
                balance roundrobin
                server  186576-web-01 18.204.8.229:80 check
                server  186576-web-02 3.83.245.143:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
